data = {
    'dnd': {
        'template': ['{opening} {middle} {end}'],

        'char': ['{name/Template}', '{Title} {Name}', '{Name}{name}',
                 '{Name} {Name}', '{Name}{epithet}'],
        'name': ['{gen/vowel}{name}', '{gen/consonant}{name}',
                 '{name}{gen/vowel}', '{name}{gen/consonant}'] * 6 + ['{gen/username}',
                                                                      '{gen/karst}', 'fish', 'thor', 'aztec', 'boros', 'beau', 'nyx',
                                                                      'cyka', 'dagon'],
        'title': ['Lieutenant', 'Lord', 'Sergeant', 'Colonel', 'Overlord',
                  'Professor', 'Doctor', 'Janitor', "{God}'s Favored", 'Admiral',
                  'Prince', 'Princess'],
        'race': ['half-{monster}', 'half-{race}', 'were{race}',
                 'were{monster}', 'hobbit', 'halfling', 'human', 'elf', 'monkey',
                 'jewish', 'canadian', 'drow', 'dwarf', 'gnome', 'dorf', 'tauren'],
        'class': ['paladin', 'monk', 'rogue', 'warrior', 'fighter', 'knight',
                  'wizard', 'sorceror', 'pirate', 'samurai', 'ranger',
                  '{adjective} dancer', '{adjective} Magus', 'sandwich', 'lumberjack',
                  'ninja', 'programmer', '{thing}omancer', 'witcher', 'biologist',
                  'gentleman', 'lady', 'aristocrat', 'disciple of {God}', 'cowboy',
                  'companion', 'seductress', 'stripper', 'druid', 'bard', 'barbarian',
                  'cleric of {God}', 'alchemist', 'cavalier', 'oracle', 'summoner',
                  'witch', 'necromancer'],
        'adjective': ['{adj_bad}', '{adj_good}', '{adj_neutral}'] * 4 +
        ['very {adjective}'],
        'adj_bad': ['zombie', 'giant', 'fiery', 'tiny', 'demon', 'possessed',
                    'marauding', 'angry'],
        'adj_good': ['eternal', 'all-knowing', 'immortal', 'magical',
                     'blessed', 'holy', 'mighty', 'heroic', 'charismatic', 'legendary',
                     'exotic'],
        'adj_neutral': ['stone', 'enchanted', 'ancient', 'giant', 'elder',
                        'bumbling', 'inadequate', 'flabbergasted', 'horny', 'naked', 'nude',
                        'frozen', 'boiled'],
        'adj_land': ['land', '{adj_good} realm'],
        'enemies': ['a {group} of {monsters}',
                    '{Title} {Monster} and {number} {monsters}'],
        'monster': ['{adj_bad} {monster}', '{adj_neutral} {monster}', 'orc',
                    'dragon', 'demon', 'goblin', 'kobold', 'giant', 'yeti', 'kitten',
                     'succubus', 'incubus', 'rat', 'vampire', 'bee', '{thing} elemental',
                     'kraken'],
        'monsters': ['{adj_bad} {monsters}', '{adj_neutral} {monsters}',
                     'orcs', 'dragons', 'demons', 'goblins', 'kobolds', 'giants',
                     'yetis', 'kittens', 'rats', 'vampires', 'bees',
                     '{thing} elementals', 'krakens'],
        'animal': ['elk', 'bear', 'alligator', 'tiger', 'vulture', 'lion',
                   'wolf', 'direwolf', 'duck', 'kitten'],
        'group': ['swarm', 'clan', 'band', 'gang', 'horde', 'army', 'harem'],
        'thing': ['{adjective} {thing}', '{animal}', 'potato', 'steak',
                  'burger', 'sword', 'anvil', 'flame', 'breakfast', 'bag of holding',
                  'staff', 'wand', 'dildo', 'gemstone', 'axe', 'shield', 'spear',
                  'bra', 'airship', '{monster} statue', 'painting', 'katana',
                  'breastplate', 'helmet', '{animal} sausage', '{animal} sandwich',
                  '{body_part}plate'],
        'activity': ['killing {monsters}', 'training {class} novices'],
        'achievement': ['ate a {thing}', 'ate a {monster}',
                        'bested {Char} the {Title} {Monster} in battle',
                        'recovered the {Adjective} {Thing} from the {adj_land} of {location}',
                        'defeated {enemies}', 'tamed a {animal}', 'found a {loot/item}'],
        'alignment': ['{Order} {Morality}'],
        'order': ['lawful', 'neutral', 'true', 'chaotic', 'green', 'badass',
                  'moderately', 'technically'],
        'morality': ['good', 'neutral', 'evil', 'badass', 'canadian'],
        'story': ['legends', 'stories', 'the {adjective} scrolls', 'tales'],
        'location': ['{Adj_good} {Place}'],
        'place': ['flooded {place}', 'woods', 'forest', 'hills', 'ruins',
                  'mountain', 'ridge', 'valley', 'cliffs', 'steppe', 'plains', 'sea',
                  'pillars', 'waterfalls', 'brothel', 'dimension'],
        'malady': ['{thing} allergies', '{monster}-rot'],
        'god': ['Pelor', 'Asmodeus', 'Dagon', 'Cthulhu', 'Nektor', 'Nyctasha',
                'Atropos', 'Chadde', 'Voldemort', 'Your Mom', 'Azathoth',
                'Shub-Niggurath', 'Yog-Sothoth', 'Nyarlathotep', 'Yig',
                'Mordiggian', 'Eul', 'Hammond', '{gen/Karst}'],
        'relic': ['the {Adjective} {Thing}', "{God}'s {Thing}",
                  'the {Thing} of {Adjective} {Place}', '{God}\'s {Body_part}'],
        'number': ['two', 'three', 'four', 'countless', 'many'],
        'body_part': ['arm', 'leg', 'chest', 'breast', 'groin', 'head', 'nose',
                      'ear', 'finger', 'toe', 'torso', 'knee', 'elbow'],
        'epithet': [' the {Adjective},', ', the {Title},',
                    ' of the {Location}'],

        'opening': ['{Char} is a {Race} {Class}', '{Story} tell of a {Class}'],
        'middle': ['who specializes in {activity}', 'who is {alignment}',
                   'who hails from {location}', 'who suffers from {malady}',
                   'who worships {God}',
                   'who has a {Adjective} {Animal} companion',
                   'whose {body_part} is {adjective}'],
        'end': ['and once {achievement}.', 'and quests for {Relic}.'],
    }
}
