class DungeonType:

    def __init__(self, name, adjectives=set(), nouns=set(), epithets=set(), monster_reqs=set(), monster_opts=set()):
        self.name = name
        self.adjectives = adjectives
        self.nouns = nouns
        self.epithets = epithets
        self.monster_reqs = monster_reqs
        self.monster_opts = monster_opts

# Ideas for dungeons:
# Normal: dingy, cult
# Rare:
# Joke: Bureaucratic, meme (steamed as adjective)

types = {
    DungeonType('cave',
                adjectives={'dank', 'deep', 'dripping', 'hollow', 'murky',
                            'subterranean', 'sunken', 'vast', 'vaulted', 'yawning'},
                nouns={'burrow', 'cave', 'cavity', 'den', 'hollow', 'karst', 'maw', 'mines', 'sinkhole', 'tube'},
                epithets={'endless echoes', 'gaping proportions', 'rocks and dirt', 'the bioluminescent', 'the collapsed god',
                          'the earthmother', 'the mole mother', 'the slimy walls', 'the underworld', 'unknown depth'},
                monster_reqs={'rat', 'troll'},
                monster_opts={'ancient', 'giant'},
                ),
    DungeonType('clockwork',
                adjectives={'clockwork', 'engineered', 'grandfatherly', 'mechanized',
                            'meticulous', 'precise', 'repetitive', 'soporific', 'swinging', 'ticktock'},
                nouns={'apparatus', 'clocktower', 'contraption', 'engine',
                       'factory', 'gizmo', 'gnomon', 'machine', 'plant', 'turbine'},
                epithets={'endless gears', 'ethereal futures', 'hypnotic rhythm', 'incessant progress', 'perpetual motion',
                          'ringing bells', 'the conscious cogs', 'the grandfather', 'the grinding gears', 'the twelve hands'},
                monster_reqs={'automaton', 'golem', 'wind-up'},
                monster_opts={'quick', 'reconstructed'},
                ),
    DungeonType('feyland',
                adjectives={'auroral', 'deceptive', 'ever-fading', 'half-forgotten',
                            'impish', 'mythic', 'otherworldly', 'shrouded', 'twisted', 'whimsical'},
                nouns={'court', 'dimension', 'dominion', 'dream', 'fable',
                       'haven', 'holding', 'kingdom', 'realm', 'vision'},
                epithets={'hidden desires', 'incomprehensibility', 'oberon', 'subtle spirits', 'the fey',
                          'the gentleman with thistle-down hair', 'the lost lords', 'the phantom parade', 'the tooth taker', 'wonders'},
                monster_reqs={'fairy', 'pixie', 'shapeshifter', 'unicorn'},
                monster_opts={'clever', 'tiny'},
                ),
    DungeonType('flesh',
                adjectives={'blinking', 'bloody', 'cronenbergian', 'fleshy', 'hairy',
                            'leathery', 'lipid', 'ruptured', 'shambling', 'spongy', 'syrupy'},
                nouns={'belly', 'cannula', 'carcass', 'egg', 'growth', 'jaws', 'mass', 'nodule', 'socket', 'tumor'},
                epithets={'clotted corpses', 'expanding girth', 'maggots', 'meat', 'skittering things',
                          'tendons', 'tetsuo shima', 'the gravedigger', 'the sentient, all-consuming blob', 'tissue'},
                monster_reqs={'pimple', 'gurgler', 'toothy'},
                monster_opts={'pulsating'},
                ),
    DungeonType('forest',
                adjectives={'coniferous', 'deciduous', 'dry', 'forested', 'lush',
                            'pine-scented', 'snowy', 'sparse', 'timbered', 'verdant'},
                nouns={'branches', 'copse', 'forest', 'grove', 'holt',
                       'shrubbery', 'thicket', 'timberland', 'wilderness', 'woods'},
                epithets={'carnivorous woodpeckers', 'grand groves', 'howling wolves', 'humming nests', 'imminent brushfire',
                          'the domain of the woodsman', 'the forest queen', 'the high tree council', 'the nemoral one', 'the taiga clan'},
                monster_reqs={'feral', 'hogs', 'wolf'},
                monster_opts={'bear', 'dire', 'hunting', 'spider', 'quick'},
                ),
    DungeonType('jungle',
                adjectives={'diverse', 'drizzling', 'humid', 'oppresive', 'overgrown',
                            'poisonous', 'primeval', 'steamy', 'teeming', 'tropical'},
                nouns={'bush', 'canopy', 'hinterland', 'jungle', 'morass',
                       'rainforest', 'rone', 'tangle', 'tropic', 'wilds'},
                epithets={'acid rain', 'ceaseless rain', 'frogs', 'lizard-kings', 'the angry flood',
                          'the great monsoon', 'the great web', 'the invisible tigers', 'the rain queen', 'venom'},
                monster_reqs={'spider', 'lizard', 'frogman'},
                monster_opts={'poison', 'shaman'},
                ),
    DungeonType('magical',
                adjectives={'anagogic', 'arcane', 'enchanted', 'inexplicable', 'magic',
                            'mystic', 'occult', 'runic', 'spellbinding', 'thaumaturgic'},
                nouns={'archive', 'cottage', 'ley line', 'monument', 'nexus',
                       'oasis', 'obelisk', 'sanctum', 'tower', 'university'},
                epithets={'grimoires', 'knowledge', 'pointy hats', 'power', 'summoning', 'the arcane',
                          'the great raven', 'the unseen academicals', 'three wishes', "wizard's rest"},
                monster_reqs={'slime', 'elemental'},
                monster_opts={'fire', 'giant', 'shaman'},
                ),
    DungeonType('manor',
                adjectives={'aristocratic', 'expensive', 'fancy', 'gilded', 'majestic',
                            'noble', 'opulent', 'palatial', 'regal', 'resplendent'},
                nouns={'acropolis', 'alcazar', 'bastion', 'castle',
                       'chateau', 'estate', 'keep', 'manor', 'miyagi', 'palace'},
                epithets={'absolute corruption', 'duchess gwendolynn', 'jeff bezos', 'king friedrich v', 'obscene wealth',
                          'the decadent dead', 'the last true king', "the queen's retreat", 'the royal hunt', 'twinkling chandeliers'},
                monster_reqs={'guard', 'knight', 'esteemed'},
                monster_opts={'ancient', 'servile', 'hunting'},
                ),
    DungeonType('maze',
                adjectives={'bewildering', 'confused', 'encircled', 'impenetrable',
                            'labyrinthine', 'tangled', 'turtuous', 'unknown', 'vast', 'zigzag'},
                nouns={'enigma', 'fog', 'knot', 'labyrinth', 'latticework',
                       'mandala', 'maze', 'puzzle', 'warren', 'web'},
                epithets={'cheesy rewards', 'hedges', 'hidden passageways', 'inscrutable purpose', 'lost souls',
                          'minos', 'shifting routes', 'the corrupted architect', 'the ever wanderer', 'the high hedges'},
                monster_reqs={'rat', 'minotaur', 'hunting'},
                monster_opts={'ancient', 'troll'},
                ),
    DungeonType('mountain',
                adjectives={'alpine', 'apogean', 'craggy', 'hypoxic', 'lofty',
                            'looming', 'skyward', 'steep', 'sublime', 'towering'},
                nouns={'apex', 'ascent', 'butte', 'crest', 'mountain', 'peak', 'pile', 'roof', 'summit', 'wall'},
                epithets={'black snow', 'dueling cliffs', 'flying rocks', 'a thousand steps', 'many peaks',
                          'the celestials', 'the cori celesti', 'the first sunrise', 'the heaven piercer', 'the olympic crown'},
                monster_reqs={'giant', 'yeti'},
                monster_opts={'dragon', 'ice', 'goat'},
                ),
    DungeonType('nightmare',
                adjectives={'foul', 'freudian', 'hellish', 'horrible', 'illogical',
                            'macabre', 'non-euclidean', 'screaming', 'unsanitary', 'vivid'},
                nouns={'abomination', 'chorus', 'darkness', 'gehenna',
                       'haunted house', 'havoc', 'illusion', 'ordeal', 'trauma', 'void'},
                epithets={'a thousand eyes', 'abominations', 'brown pants', 'grasping shadows', 'terror', 'that which bears not thought',
                          'the night terror', 'the recurring thoughts', 'the screamers', 'the test you did not study for'},
                monster_reqs={'abomination', 'imposter', 'shoggoth'},
                monster_opts={'ancient'},
                ),
    DungeonType('temple',
                adjectives={'angelic', 'consecrated', 'divine', 'hallowed',
                            'holy', 'pious', 'pure', 'righteous', 'sacred', 'sanctified'},
                nouns={'basilica', 'bethel', 'cathedral', 'enclave', 'pagoda',
                       'pantheon', 'parish', 'shrine', 'tabernacle', 'temple'},
                epithets={'fallen prophets', "god's whisper", 'golden light', 'his favor', 'martyrs', 'saving grace',
                          'the great sacrifice', 'the metatron', 'the pendulous thurible', 'whispering shadows'},
                monster_reqs={'angel', 'cultist', 'sacrifice'},
                monster_opts={'imperious'},
                ),
    DungeonType('tomb',
                adjectives={'ancestral', 'austere', 'ghastly', 'ghoulish', 'grim',
                            'morbid', 'necrotic', 'ominous', 'rotting', 'sacrosanct'},
                nouns={'catacomb', 'crypt', 'golgotha', 'hypogeum', 'mausoleum',
                       'necropolis', 'ohel', 'sepulcher', 'tomb', 'undercroft'},
                epithets={'adorned emperors', 'ancient kings', 'cadaverine', 'cryogenics', 'dead gods',
                          'the departed', 'the fallen', 'the gone but not forgotten', 'the soon faded', 'the unburied'},
                monster_reqs={'ghost', 'undead', 'skeleton'},
                monster_opts={'ancient', 'rat'},
                ),
    DungeonType('volcano',
                adjectives={'ablaze', 'ashen', 'blazing', 'burning', 'conflagrant',
                            'dormant', 'erupting', 'glowing', 'scorching', 'smouldering'},
                nouns={'crucible', 'volcano', 'crater', 'hotspot', 'vent',
                       'mantle', 'geyser', 'explosion', 'flow', 'tor'},
                epithets={'endless fire', 'lava', 'the shining finger', 'gaseous ghosts', 'the coal walkers',
                          'the first ember', 'the empty pyres', 'pyromaniacs', 'searing sound', 'the licking flames'},
                monster_reqs={'fire', 'elemental', 'dragon'},
                monster_opts={'lizard'},
                ),
}

types = {t.name: t for t in types}
